#!/bin/bash
#
# Clean up the tree
for x in autom4te.cache Makefile configure config.log config.status configure.scan autoscan.log; do find -name $x -exec rm -Rfv {} + ; done
find -name \*.so -exec rm -fv {} +
find -name \*.a -exec rm -fv {} +
find -name \*.o -exec rm -fv {} +
rm -f dvminigrab dvminigrab_hd
rm -f *~
