#!/bin/bash
#
# Most firewire cameras will happily take libiec61883's channel change.
# Panasonic DVX100's on the other hand have a fetish for channel 63 apparently.
# Specifically, attempting to just change the channel will force it back to 63,
# you have to set bcast_connection=0 and n_p2p_connections=0, change the channel,
# and then turn on n_p2p_connections=1 as soon as possible before the firmware
# sets it back to 63.
#
# In case this shell script doesn't succeed the first time, we retry up to 10 times.
#
# This minor bitchslap forces the Panasonic onto the desired channel.
#
# -- Jonathan Campbell
#
# plugctl-panasonic-force-channel [port] [node] [channel]
PORT=$1
NODE=$2
CHANNEL=$3

if [[ "x$PORT" == "x" ]]; then exit 1; fi
if [[ "x$NODE" == "x" ]]; then exit 1; fi
if [[ "x$CHANNEL" == "x" ]]; then exit 1; fi

PATIENCE=10
T=63
while [[ $(($PATIENCE >= 0)) == 1 && $T == 63 ]]; do
	plugctl -p $PORT -n $NODE oPCR[0].n_p2p_connections=0
	plugctl -p $PORT -n $NODE oPCR[0].bcast_connection=0
	plugctl -p $PORT -n $NODE oPCR[0].channel=$CHANNEL
	plugctl -p $PORT -n $NODE oPCR[0].n_p2p_connections=1
	T=`plugctl -p $PORT -n $NODE oPCR[0].channel`
done

